---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csi-driver-nfs/ks.yaml
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
