---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.(ya?ml|to?ml)
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
