---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backupe.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
