---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: downloads-add-kubexit-to-jobs
  annotations:
    policies.kyverno.io/title: Add Kubexit Volume to Job Pods
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod,Volume
    pod-policies.kyverno.io/autogen-controllers: Job
    policies.kyverno.io/description: >-
      When creating Jobs with sidecars, a method of coordinating between the
      job container and the sidecar container is required; otherwise the Job
      never completes.
spec:
  background: false
  rules:
    - name: add-kubexit-volume
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - "download"
      preconditions:
        all:
          - key: "{{request.operation}}"
            operator: In
            value:
              - CREATE
              - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    volumeMounts:
                      - name: kubexit
                        mountPath: /kubeexit
                volumes:
                  - name: kubexit
                    emptyDir: {}
    - name: add-kubexit-environment
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - "download"
      preconditions:
        all:
          - key: "{{request.operation}}"
            operator: In
            value:
              - CREATE
              - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              # FIXME: if we can figure out how to match name:
          # !gateway-sidecar we can do all of the mods here
              - name: gateway-sidecar
                env:
                  - name: KUBEXIT_NAME
                    value: gateway-sidecar
                  - name: KUBEXIT_GRAVEYARD
                    value: /kubexit
                  - name: KUBEXIT_DEATH_DEPS
                    value: backup-job
                  - name: KUBEXIT_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: KUBEXIT_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
    - name: add-kubexit-command
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - "download"
      preconditions:
        all:
          - key: "{{request.operation}}"
            operator: In
            value:
              - CREATE
              - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - path: /spec/containers/{{elementIndex}}/command/0
                op: add
                value: kubexit
