---
apiVersion: v1
kind: Namespace
metadata:
  name: download
  # annotations:
  #   volsync.backube/privileged-movers: "true"
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    #volsync.backube/privileged-movers: "true"
    # vpn-routed-gateway: "true"
    routed-gateway: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
