{
	"data": "ENC[AES256_GCM,data:gQ00h/6b+nmC+CZ0gEHVKucW+/tE4KaQJbh4orPhCpt+S0tVJgCXmX7j1gwpP2ngbtZcwe78nZjY/ecn8TXWrUi3dwD7xQkH2/VlsZLutcpNCYBy/q5tdk9piMkSey3A3WR+t7f2WP8A4cdIZG3G3LAWIZS/Jy7zR8ZmyG8TJUiPXLykcPMd1iRk2YT45aGO1jXLnrlkH05Gs3dip/M2F2U1A5jnb8vRr0pSIml24iwfQEMcpJKdQwBledIV/sNJK8rn7YwBjyEaxswxoi+FYxWYmKv6hTw32J0KuOdztqZGBUUBlsX/JA2keQaOGl5kTHoLU6ItyFi026Vg4aVDKMQwbfXhpodQQff8+ZgEhemZBLjDe7Zc4ilt4GMsC+of5nO1MH7vL6wwWBwlBCjyCSyaVRHRS8zw515fjWUaSyIDVEM/c8NFgaypVlmzFdcAc9Ak+UkOhFMudOFNgSWlhjJyUcUBohQG1ammH+8aG6Ggc3DLC4hNRHPCAupWuv7c/tPXQQ6kpAeVX8+l+X4KsQC6pCQvvp4Rf7mOJNX3SckijZk93NVnIxSNMRKOf6tS7e3JlCm3P95O/FqBqqAsSW0PwlE0FiCxuJCg6CSOT7j0pPkGUjo+PGB4zIuI0/7EOcFLL9rz7aED23crJhiPY8ixdnf5dgRira1CopotRaGOsCNvOpD4CTGTt40tdm/A/8OVxZ3ZjObwYdMUpehFwVE10e6opRR7q45otPKuLTi/1aUjDdOWGLUK0faF4+Dvfr8+ULKFoqWpZmt4FsJn3K1+ZpvjaH51u8rTMHHWuDk/vzhVIfSqG6i3zEr8ogW0PiOlB8ca4NEo1UFDZ6Ni+yE17nU23ZsCQEIPZNkzcnodrjPLPjO+ogHJIHV1xJjlKWHorhcsfjCUbAGOZ1kjijx+EmKKswLjyGXKXRKgW79nUmpb0VXVW8FoypC40Mz2gPV8H0eEvZ8WHW9MzD8DfD+gcK/Mlb4/ofZjtntX74UOMh/Bxru/ZfJ9e12h0PhmFRbqByzmVgTxKbZxjtEATH1isq1m2y4p3PeqIDg+tOuVKaCPoiAQRK8rBfSJZaO2Y6UHqou7VOW0roWnbE/yQYSptZiLMuZzbHP1UYI=,iv:JFkbPSx8K1eOrlOnmeywCEYoc+wjnx8HOL4pzfDE50w=,tag:xG/czPV0Kk0yhktyEDB9eg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQkdDanZkSTRHbGRSbU4y\nWlRkcHFMNzJVdDhmSDQwYUdJNThuQ0VXa0U0Clc0OE5vejZpcEszZ2IrdTV6OHVT\nV3hjZ2xNSGpkY1hNQlJ3WmlNb09kaW8KLS0tIGp1bUZoNnpSMDRmOUlNWVdpS3ND\nL1hBODJzVkVZUUIwN3ZNbWtaUWl1Q2MKh5b30X79HaoIZorU+9V7uW9/QLa1K9ll\nk/6NHMkCLXavFNmpMGfoPkrRkObos6DQLqzSUDV8pYqQztYOr0XbbA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-01-03T20:46:43Z",
		"mac": "ENC[AES256_GCM,data:uaRBmVFDYqXQNEIeNSZT9AIq10tpUR3Hw1mLQGBw9NZX0jogReza+yFGoiBzTzZmSUzZ7Box54iQxER3TSL5pJUMLQrI0niuo5Bo668/q0t+ayDE5VbQbddjIk6DaxEW1tYtYAffIERKa+enr2G93eEot2ncqtvUJ2x8ZsbO5QY=,iv:tLCpZzoJGCjRmnFUG4yPec3Q+1FBsojsRJZR0Ty3G30=,tag:Lf9w/4rvZlP7Y7J7QdvBYw==,type:str]",
		"pgp": null,
		"encrypted_regex": "^(data|stringData)$",
		"version": "3.7.3"
	}
}