{
    "data": "ENC[AES256_GCM,data:V822y1RBdhDOk5pcxPz3cv4bIZ5/oSRAd5tPKqnqVfYfSnWS3Ml1RZ0fT3cWMru4G7gz72o/SCLsJw4I+ZpNgInEuLl9+/F+BRkkq6hU79sk4dMefyLBMahPc52ezXUGNFjRvj7MUPr44v74nq+UzCZ0zF2DCSWGCIHd8wDk/V1vld+s6EiSL5u78ovu9vBRhe/XmLXjtW0rr/o1Aj7WDRlkrnpkjnVbOe5LDjCS0Z9VaYNvnSPqN0y7/8iCaMcb2KWgQBnmlq91bv/lZcAdvuE1C6oEWTuzZiktj/KFx6y/gZrVtj7BcCy37BBsLEjfhhp+JRY5QECA7eccGEMxtjzrBkucccWmsGlMNB7ocFAu9B9j718btNvj1dFu1LN1yNEszo8VuYrwUSM//q7ZjrgHIkGPiKqra/c9iqbf/0XH4FQOYBQUKeqG/nuskAmJkCEHVXat/nXhoqmyZVXK1nqbf+NW//gZx9vP+2ptEgBupLgtQ8CykglqTiTWVZJKlJYbMvK94eC1qSQtQ+SDxG/ae+k3KbQ2xS75wMUxqtwZa98DauNa6GImYYANRE4DTPOkZs+uiwLKVw++V3IXXZya3yxCw27JL5GfABgdXdBVz/DZhRd9JHQbxfPeguOj2AnwBNM0p23GcaKEx4ksxnJNODB7Ogp7bvVyUwrLmQFyvkMtNLREC56mRoyy3pqvMDFLeTGcW8T3Weyh7upJnYGv9WS/ZpRojvNRIgKkLV2DKIsF2ZavMN5rZfeGjkLiS9lPnDeHoEM0R5WnydvafjBOtl7dnj/bmgp3syRtjiEMesRfaIabEI6eua0sFKPuoDw+UUG0qwPqlYKEt21nWweur36HCWCfVG98XFskWVNGeHXXrOyXTCNS77hpW9tWs2oZDkfYxvV+hcrsYNbpKSe62Uw33QGihR8NIHIrrQrZOm9cZKWIUIRQ710dRmEIuFY14FW/8A6SGO1rCqixp7qrKRSuy+0YP/RpYXI4teJKQArB8a9Cckle82Gm/lKo7sPnSyz0/GkfceJ0xwzwxuKQZHnI4bryrS1hVqwbFyZQyjtTgS8BWQA53sBumPyxLmyYqwOMH3/5sIIJOMVEoEL8I9b6mMTJbRhCEOg2FRx8Q/GOswrxFVAnwzJdoeieg7BJwZAdyFKFrZUUeuS/,iv:6PgRZNFkWW6laKZ6g/mrQ68SGyOQ196V9ukATt4Ecjs=,tag:lPKua4Y7MJ+kXn0dZjEjrg==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQkdDanZkSTRHbGRSbU4y\nWlRkcHFMNzJVdDhmSDQwYUdJNThuQ0VXa0U0Clc0OE5vejZpcEszZ2IrdTV6OHVT\nV3hjZ2xNSGpkY1hNQlJ3WmlNb09kaW8KLS0tIGp1bUZoNnpSMDRmOUlNWVdpS3ND\nL1hBODJzVkVZUUIwN3ZNbWtaUWl1Q2MKh5b30X79HaoIZorU+9V7uW9/QLa1K9ll\nk/6NHMkCLXavFNmpMGfoPkrRkObos6DQLqzSUDV8pYqQztYOr0XbbA==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2023-01-06T19:55:51Z",
        "mac": "ENC[AES256_GCM,data:hsC/fdUTJNrmUIYQYcD3MzQO5ivkAqI9CTQE6keeelW9ojSHf3vTdfKB1Ev5+avZ+svCafUhQkeGnVPzmpVSfeUeioCWAu7bPfJlGsDunGZoGnSTEBzskR5lfnz8SnZJafrgOLgoC9JNF32jewBJlZ7NCpRRsyshbGjXgrId/Ao=,iv:GGX5bi02v1PQoSj5sNYu1AXNjGhHUlz8+ochiG0VJK4=,tag:84RYBql2jIPSQo5CrmLYXg==,type:str]",
        "pgp": null,
        "encrypted_regex": "^(data|stringData)$",
        "version": "3.7.3"
    }
}
