---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./postgres-secret.sops.yaml
  - ./secret.sops.yaml
  - ./helm-release.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
  - ./patches/postgres.yaml
configMapGenerator:
  - name: authelia-configmap
    files:
      - ./config/configuration.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
