# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia-postgres
    namespace: security
type: Opaque
stringData:
    POSTGRES_URL: ENC[AES256_GCM,data:1OUuCkLt/f/7YbM3pEGJOux9SxLeMnilHcoVJ/Tr2YX5Obo=,iv:BVY6vdcQv/e8cgJBQoiDZkvpqh5f9Qyal8vinvdigrs=,tag:ZDIUMGD9Fmjjl8w+Ad2jCg==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:WRusTMCkP5b0Oe4v9OUca450qLktHlY1c8S6El3bEkMymF0=,iv:iv1CrenHKQsX47wRh63VLmVJYF3qduCtRemgVMJmJWY=,tag:2YZv2A8hZyfBeYh1cKyNEg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:hVrsTn7E+ok=,iv:0hz37x5EEAKpiq57rX6GniZmOvhmbOIytCiIaIXAmhk=,tag:+Z+aVGeU8FmWO8VkKz/1xA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:2Wb5GSzoVvc=,iv:GDXBEk01Fkkzpw84M1+rhp1pRPiO2/tfPgj0oJzUIJw=,tag:qsgusfSP/Sh0cVqwiRj/Aw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:kuS7/JBvg4YZsgJ52TuTy+Jk6wfoQiqP+WhsJDGLXLIxLg1M/2VCMw==,iv:l6FUyaaiP/7BZVhA2EI+w20C7GXSfsDkS3tGvks9DYM=,tag:5lTjCx/lQZ0ilL91B9dk+A==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WhGsLH14GclDt0okkU+3Q+M/UU6mZYE6sCMkm/eCuTvL54SVqjIMzA==,iv:1UcqoEQ6GJesMdM/6oEkvhqoqx8YicC5xwozP3I9jJ0=,tag:MVsRnisV0TC+J9BVtZc6zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbzU4enA4OXlxaGdURkxN
            TWJNZjZMZVNTem83L3NIVUptZ2s1bVZNbkFBCnoxMHhrRTM1U1hZQnhCWjJONmJu
            ZE54UXJRQzRGZ1NIbGZmcVFRTzlUUm8KLS0tIC9xcThZMW5xMW4rZjhKdjJuZElL
            NmxaM0kyZ0NtZzFLeW5CTlZQRXUyVFUKAwYx78dVgoFWTaPYwS/6LE7MGs5cGwG9
            2/d2gWM64RLSm26Zv0pRT37/ijonbKMK3jij4E1M9Wto1pxY5SQu/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T21:06:40Z"
    mac: ENC[AES256_GCM,data:3kVy9QlnR88s/9ufOxSnM+T9jH9X8ErcsUMG3DBRzrfhvNN8ZMl7elK16GVFZ61OhgXvB0m9jrJghHdAEAwY7L53tAv66nXp6WTckTIG4tK2kyVTviG3fPJdyE/N50l/2SMEaBPTrnpCz4+m685UFJ3KskP5VHi2S3f0Y42NzE8=,iv:CGKKWcZnQN43zx/mel6yKZK29PqxbP90AMUMrZFEZcI=,tag:DeXMFRO2dh3UpxU+ILt21Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
