# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: security
type: Opaque
stringData:
    # Authelia
    AUTHELIA_JWT_SECRET: "f4a18e8c27bce29705b064549f8156a7db3fa03bc163c78bb0a13c751974e12713cd1fd4e8741f895638986da09acce3a9dc3e295d476216d47e9a9655dab82b"
    AUTHELIA_SESSION_SECRET: "913e32bcea765548a5bc03194c5b0ebe524afc2d8362cdabefbe1609f2fa28f6d73b330ee4bb12059b5fefb4b1dab2f997133f91a77d2d376c1c9aa2769c06ff"
    AUTHELIA_SESSION_REDIS_PASSWORD: CcBXNkYtoWZxbBAuUEcxE3LP6ZRTyYvNLwZTthag
    AUTHELIA_STORAGE_ENCRYPTION_KEY: "20e6eec04f1225aa4b01aa5fae6544d92e65c3be179593744c04620b17bf646d9b02491cf32d0643bce67c903aaee4f096a30ceba27354da58dbf20fb85ef151"
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "ABTLaHsen6qUzbX8HngCaXogYkB8mxKbb9UVRaqh"
    # AUTHELIA_NOTIFIER_SMTP_USERNAME:
    # AUTHELIA_NOTIFIER_SMTP_PASSWORD:
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "2d7c3c42feff2cd42d969cb16477aff5d8099465dc8f49f477071a22542485cc8d7564eeeb9204ac8ac7e170461bf04706ae3ab65b720022648479ae90113627"
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIJKwIBAAKCAgEAzHYy4EHBk3/M69rWpY5Sg6rkTlHiZW36B7csWrqmNv3uTBVp
SVFrgEISKJFtLGztWAbdm+189ZLFBK+BQJXnRuKWEEBcfhU35yMp9hE3Bhqnw+bw
n5ZgRvh9O5VgsACRBobtcKkWSWfnBrGT5uIQ7XNkTHAZiY+n8wx9WJEbL3hn7o05
OlDFCeppTrxK9wE2df+p5Tku4nFxlIGm++ddGM2Kd/kI09OcbF6d7adGSJIW5jBn
ObFzH3C791yP7PSjN/WyYwi94E24CGj13vV4U7hubebWO+cwBlijQaPuykQrwZZ/
oWrcRtoVzuzYO+IDiTBTC5IEtZEFdcvycxabhF6qv3Acj+oxpkaC419iQpyhUej0
hqaUbbKb1+IdGXy68inh0wb4YHAeE8dfpKwm6+z4pcqAMrHHMMGBiZIVr82EaHQh
8Xt2MFMiKfryhlH3JsgIiWv1ALGmw6IqdkHuGebfX+noi3VDXhCvtRL+RyMYBMJl
RMq57u6nCmGmzhu8NxYoAbMWcwGmi5a+gzNwp/vF3xz4h48qaw+wr/sEE92RGrBa
VPDN6qMCmejL4m6bAqqdmXDPtGO4IiNXPYuVZlywUIqFEC2LRpffhkDhxCJ/HB72
K6ODyGWHCbpAq7wShT5CpCQ//BS1G6JjUH+FYgaW1vCmLdTJbfKB7LGu/DECAwEA
AQKCAgEAsP69ag7iYSpoHeByohzDZ4HfY8FU6BM9N8Kk3eHoE4Dc8fYzD6oxEnWf
vIiv5p5hFCvVWa9L1lZ4wWag0GU0MdPirizZJLh/jVKOd5pNdLZMdrULpksKC0X/
Oz5D1fiXkvvovfdR+Le+cbf13g/jMXsL33PHV6MJc8hjFfF/hCeKaSLN4KKc/8lx
4hv0FUFygNGSpIFNCe/EsBdQk46ks9zyuorVznHIXrPFqT5+BEKbGifapEHt89Cm
lysE2M6qIL5L75lYrbz5zCX4eksrH+ZviiojWPX4R/YhVahxBZ3f9xSuZfDYwWj3
Kgsz4Rr1jqRLr592/iqNfHzR5Dk04+QPtDCcI5i0FeVPogUynqyaS54LINpL0pbt
YMo//4A4k/95arwBgiiSQJrQJN2z63w/TOD2SbXnDu0WYEb6OJQAvk/EsWev177/
lG2VMx+SwgxDkCLTDxfecvY1FTwnMGMqj5Bx10qK73UaLo+46r2CfWBWshcH67yb
ue+5kJiAkMju6n1Zpx3bwVTBf6UAVDcfyjE2BrA41qMKRFj4fXrINP0p2eqJgUMz
pMEBIMvJlizPQ1fDxNIGQ2dxF6H3lLfmd8ARml+InemoC8ol9UIKvDxqMxDLKRpw
BwNJtucCWdQo5CB78v6vyEGdZ48WDO3FZPbTZsEp6/AK8+1Iw7ECggEBAPQ8aIkH
FIV2x/fB+5MgUIBcLnM9MMQ2JDZcBLwD3yPs20/mkpzOLGSgIj3eYEP6GUh0F45g
KItx9JOjYGg4XftKpCeWFvo0qc6cTBtrnkqF1SG6ab7J4HRd0J+DxuCC63LhZR3F
Tyy0vvEKjON2/ZZkSAeRMKDlduOHH8g/E11oRi2ZuniEWWbeUaQi2Tfn+6EEqyIa
Ow4zK5S9QWH/cCt06jSk7QF9KQQtnAhyllcYRo/qwgB/lJ7ooUhYmxlMVt34Vw2n
ZQUDBUasNDHlY1BOU/pnkTM3tKkBdvomi2b4CrNlSZ4vab2+qCRxF1xKS+2Wnvvb
9/RRKVK6PGRGA20CggEBANZPWO+zd86OLNtqRD0sENx3InBB4QxVs1ZopRoQpYKT
XUaWcu7olEjEnYjerdtpr0vp+ZZc2GHLHespAFDmFIK8AFH3M7CpaDxkK8KmRxQc
AV/jD8Jz0OTwfn+FhrbLk6CzayfAF0s5EAgmoJSbmGowxC9cJIbGjcgZtZ4WNk9M
6NQ7wjrq4hmoKR+PnmIuaCzWO9cqYLWCinHausY/DMrA6OgL9RIhhrxDFs8LX8VI
3k5lENTUdcjQCdM6BX4ZCW7Gj2LXa+YcO0vk5MSnoTCgF3FCwdz8SRC7HpQBAnY6
QWeR+Sd4wD7hlzplyeDnwsuytNSVX1/flSyt2wPunVUCggEBAMZyNvXv3Mq8wqoa
4dCflwlU3SEhfPhQjYflqKsj8jD8iQ4Y6NOj6gow2uGuSEWzdsuaGHHEy+zRwMod
G35THnnKIitQFodiNv77nBNDlDA1IgHvt3AgE9I5UAPsTLGrbqe/YCuaYESQ7/xm
eCdyTYXfIW+UlxCEod8psbdBGPjyeuMeX5cA4qtkxK0664gzZA9m/a4N5iIZjbWj
OPbpWDjXHF1+DF0DV0pfzMJIaMOHo/3X354MC7Q6jKF97TfXAVYGLKWZd8lktOrB
jP9lxRZBLpbtg9s7zfzshcGng+k8bWVqTTDMkXxs564EfditPZhko/U8u/G16H+h
duR6xtkCggEBAKrgg5pEb++rX0rn9VcNLriK6VO2w5lRL/hi4dnhkgaGN6ZTyXqC
ydEnrDB41QkQwGv4OEDS8Nkw2j8p5w2aFpqTCnJQd8+RlAIrINVIPX5kQhhRdLxo
GhShSUumjN5tfd1xkawVNr2M1yKYogs78RAiqBrXDmzEHkKBdVWCgnVCbpbiuyC9
LeClO3zlx7SjKf8uJnKOYKP5XSgg7jGqDioQHOUAu7xkLQkpOSOG/yrPyimZ3gzF
BtFCR8M7DSwZDHNeMO/vsiG9Ou5tqJbAzf52d5qgTvFD24JSoLQEBhF8q6/ILXBy
kF7TAwDWLlx8js5aRGMIYw6PuGLykKIW/S0CggEBAJuF68SuN6IMVceMr2a2s86b
lLwBAu3os8KNdmDRQSfvAPzs/a3xXf9Cj/i9jD75nnGkZoO8eVvEHsNJSQDb7uTt
F1+hL3ne/Z6DpQ4pPEGSz+dAJS5/ClunbolZRc+vws7umgxHMwYAF5sc4+hiW9K4
uaYqckdrl6vOGgT9ZmUfUYhaA0WRu72QPOm6PIm6f9RTR4q2SOSKEDGJKWSswGdS
0KxQLqSFzydbg0NyhhtDiySfnI2B0f2adC/kw9+jRFp2RMCEwHMGL1l+67ruS9AF
df7Am/fRDCDfDsQ9g6nq6Z/PKl+6sdUvkIQgSMFw5u6/h76HTPOalC18egREcow=
-----END RSA PRIVATE KEY-----"
    # ODIC
