---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-fast
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.26.10.5
    path: /volume3/k3s-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 1Mi
