apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData:
  MINIO_ROOT_USER: minioroots
  MINIO_ROOT_PASSWORD: "QrjZpBTs3vaAhqRiCtmYjmLZxj6wqgT8GekVfpTQ"
