apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:9BlUjC8rL1Aj,iv:7FQl+4tr0C3CfnGL5+oMVUTw+swZLxc2njurXduGm64=,tag:t/IZuw9ZqAVSuWQ2lu5cuw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:k6CAHWTTTgEhsv3B+v2dXvF+Fds=,iv:VzECjswifl6qmtMrJsX8KwjKzzigmIpYSfAd/B4+ff4=,tag:S5i2C46WlV4psIP8Bk8/2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkk0WDZvT2xjZkdGZG9C
            VEVoT2doMEk2TkdiMmtzRGsreHF3ODRuM1JNCnhKa2JZT2dibXZlRjhZMHZZTHVB
            RTNHY0ZUN2tTRElpYnc2OUd0Vm9DazgKLS0tIGlYVHpZa1Q0YklBTkVoU0JOTWZZ
            WUhhL0lPSFJRU3FPWHBkTEI3L1lVbjAKxU/hZiJV4L1kz/Og30OQSjWqDWGh/8lq
            qyEIoY6szg3Csk5ShERTre3QN3rE/mlLuEqJU8+qqzB1B4qKYtabFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T20:44:34Z"
    mac: ENC[AES256_GCM,data:lpIrgFUVaBT0ObCr5WxB+nV1LtlxCxfwVNWQxOuPTHk3dpz1pFXQqTkysKSIIYZgQ08b/FDEqJKWPLJclhs2EIXYkEhZx/aSE1V0dco0pxZq55gCY9LjBRJqOfveisdW6cTtxNjOTMwO3Eo6+1BCL+S7m8Q83OJV3pERPJeTnPc=,iv:pB6GUv29/T0Erh17eRq724yocjYHevFlZT3aXwjVppg=,tag:1MU3QhnE/ZlaAYcmFGauLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
