apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData: null
# MINIO_ROOT_USER: minioroot
# MINIO_ROOT_PASSWORD: YpT8fP3fPd4CUUP3tpZq
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkk0WDZvT2xjZkdGZG9C
            VEVoT2doMEk2TkdiMmtzRGsreHF3ODRuM1JNCnhKa2JZT2dibXZlRjhZMHZZTHVB
            RTNHY0ZUN2tTRElpYnc2OUd0Vm9DazgKLS0tIGlYVHpZa1Q0YklBTkVoU0JOTWZZ
            WUhhL0lPSFJRU3FPWHBkTEI3L1lVbjAKxU/hZiJV4L1kz/Og30OQSjWqDWGh/8lq
            qyEIoY6szg3Csk5ShERTre3QN3rE/mlLuEqJU8+qqzB1B4qKYtabFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T19:31:06Z"
    mac: ENC[AES256_GCM,data:9N2V36EuJnyT55E3yR/LLQLB815DiF1UsLuCgG31iZUE0DZCfIgQHEV+oj78bqbQFhel5V0XRlGNCCbFP2aiBlpEW5fgK4yjdY3z8kI7vbasufjD9qlMAkSAI53YEFqM+0Uwhqn42eG4PTU/kJSRZtHbCJqem4MtlNt7ybhkTqI=,iv:SN3LGt7PkdL3JN4rApeth2oCxkDroxIhxF2Vp5tyLOk=,tag:Vjymz4JGHz1k5WnozwYrbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
