apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:3ifDgyn8Z0ze,iv:uhOwurxVV7kI2JjuCgH9tuPg9dSa23LgXgyvPSDgGNI=,tag:Bo6JWDAOCtRO890EV7CeYQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SMBeCc5uwa6XtRNjvB6QIKKLuYQ=,iv:joRI4NI8WiWyb2hIk2+e6oU61fbIgfO1+Oyo5fJaCms=,tag:yb1ap0LtxIaCJPpBEQgS3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkk0WDZvT2xjZkdGZG9C
            VEVoT2doMEk2TkdiMmtzRGsreHF3ODRuM1JNCnhKa2JZT2dibXZlRjhZMHZZTHVB
            RTNHY0ZUN2tTRElpYnc2OUd0Vm9DazgKLS0tIGlYVHpZa1Q0YklBTkVoU0JOTWZZ
            WUhhL0lPSFJRU3FPWHBkTEI3L1lVbjAKxU/hZiJV4L1kz/Og30OQSjWqDWGh/8lq
            qyEIoY6szg3Csk5ShERTre3QN3rE/mlLuEqJU8+qqzB1B4qKYtabFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T18:41:56Z"
    mac: ENC[AES256_GCM,data:BVFpj5dhqdJ8Oyrczfa/dqAogr1LfNnIG11YiVwL0c3vGhAWrW5w8/dFE99lCSsObxMPM09LBx5NcBIv4gKJEgFa47BLAZaczqgG9OSSdw5OuPQCE7QuyOOc4E5VuOdLAdRerMoSh5PV1gwTWKK5LiUz45Ocz/XheU/cAbQ9IQw=,iv:JB6MYyR6izdvW4jAs1EPpy7JZva4iN1+jVloBuCTNgg=,tag:BKFMVEeLMR0P6n37uOAeSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
