---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  values:
    additionalContainers:
      exporter:
        name: exporter
        image: ghcr.io/kpetremann/mqtt-exporter:latest@sha256:88316128d9d1e405c6f18ffa2521176a7640d35af3e6a648f60bdc858b393dcc
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: LOG_MQTT_MESSAGE
            value: "True"
          - name: MQTT_ADDRESS
            value: emqx.home.svc.cluster.local
          - name: MQTT_TOPIC
            value: "zigbee2mqtt/#"
          - name: MQTT_V5_PROTOCOL
            value: "True"
          - name: MQTT_USERNAME
            valueFrom:
              secretKeyRef:
                name: emqx-secret
                key: zigbee_username
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: emqx-secret
                key: zigbee_password
          - name: PROMETHEUS_PORT
            value: "80"
          - name: PROMETHEUS_PREFIX
            value: zigbee2mqtt_
          - name: ZIGBEE2MQTT_AVAILABILITY
            value: "True"
