apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:G9cFsrDhWzMRIBklroZ2KKb89KTuULDiY/EA6U7f9GtyZuogGLdpYg==,iv:iXyY6ZrKBGivkqLX19a+YTtZHg8getejOln0Gxq3Ah8=,tag:uefMXaCcoC3T1E4+mK3PLQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RARZsfZ1JV9J/d08cQQt80WgPZVBHeA0ktx9wGathI6tRSLW8ltdgQ==,iv:aP7DLDGlVbZeO47igtVkrBkuc9Z3HM18sclXNHekE8o=,tag:urGoujWJaHL03los4HeQLw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xUTC+6phIHjOosDMRQ7bMQ==,iv:miRpJGvvBDxlUwpBGXWWb7UdWw7N2vX5TdQubSwqUeg=,tag:E4PfXCQMv9WyeqJU5fAgaA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4oSx9hNsEuACZ2Q3k659TW5jlQhLcs9cygxu7iK3FuY=,iv:Np9QQGbegTSbJvc09xETHkUw5qAIiyjCGnoi/v+COKY=,tag:KnJB5A5CZKifw6IgECe63g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSXM3ZDRpYnYrZGJXcjFF
            U296aGE2UG1rWFdEb1JEczVwRXQ0bHR1TTJjClVBY2hlUVZCZzIrUEUvM1NBNndL
            Q2VjdEZMUWk5NnNVWERiekc5MWdMSkkKLS0tIEIrckVsbzBzalRFdDRoMzBNWGwv
            NHhUOC9VUHpMOTY5OWNCejZWeEkvRWcKNcOw5aClap27Uxrr216am9tnNXKeA4J9
            Ozb27zykAWTaDYIeMOu/gYOaasfziTK8G4zapQnq4ATSQfL4RalYLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T22:31:01Z"
    mac: ENC[AES256_GCM,data:BlZ5/9sOfKflhAeRuSJptumkp2QOXBTWBsGw/kGOVGj7tV9HseGmWL1ypmXu+3qFIPr+ge82r66co+Wxt9rrHBWFFKrAzqjrqLnA+qhTu/ANp0n7c0VQT9c2OFld784f9tnuApcBbtDvDqSm9XKZP9UnZ1mUpqoM9EzJehVOLjY=,iv:s36+2ume+27pPVgyssQdYiCOckbUnW8CjA5TLTMghdk=,tag:WhlbaRFuWWM2xqSBgFpPVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
