---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./authelia-redis/ks.yaml
  - ./authelia-postgres/ks.yaml
  # - ./authelia/ks.yaml
  - ./glauth/ks.yaml
