apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:WvXTvcDH6kPcuUSaCcXbMMxhOcVkFO9HrxY203Ovb3ECMtlA7t3H55YbEDumesfsVfmPI8KDHS16iwQ6,iv:1wTZ8dk4sPjURIjJN7okxkDOkn7/e8Q2ptsWPHCyBkg=,tag:U3scfbKmguco3G67Cgpt2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWxjMFhHODJmTm1tOFNW
            a0s3WXIyK3JaV1V4NEFIQVpDRE85NUh2Y3dJCjhtOFRBcE1LVHdMait4UmU3TW1q
            WnRKU0lqdDZYTUxUWWt1enRsZTRnTVkKLS0tIHR4RG1Mb0dPb3Jzblgydk9UUTRu
            WUdxOUp0aGJkeHNNUlF4ZjJRVEpOSlkKB4MdWU93tR3nIxfx7nSj1kPfrpKjCeGx
            inq/xYxdvvkVv0qOPtgU+Tq7ahF+SScEwvShuOg3vnXm/Ivs/0vJ+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T19:30:06Z"
    mac: ENC[AES256_GCM,data:0C9xDvoMUSGo+Cj4yZGsn3OA60kL/SQ5shs9UsKQCFR+FtsHz+5ziK8hQwx+0ynL1FuR4nftJ3ptQzYr1KxlVHUkot4RBT7ykdv3UEK6Icqx8aLQ3vjEh0HBW++k1Ecinh/1RKbjIBGAdHur60CrM9jCTyZI7ibnvpqkhVP+JtA=,iv:YBUbcDdz/ltXg/Vp6rGRsS8IkJTRhwTgiSjTMa/Cmxo=,tag:bVVu7hpq2VlKiCIPLCCK5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
