apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:WvXTvcDH6kPcuUSaCcXbMMxhOcVkFO9HrxY203Ovb3ECMtlA7t3H55YbEDumesfsVfmPI8KDHS16iwQ6,iv:1wTZ8dk4sPjURIjJN7okxkDOkn7/e8Q2ptsWPHCyBkg=,tag:U3scfbKmguco3G67Cgpt2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWxjMFhHODJmTm1tOFNW
            a0s3WXIyK3JaV1V4NEFIQVpDRE85NUh2Y3dJCjhtOFRBcE1LVHdMait4UmU3TW1q
            WnRKU0lqdDZYTUxUWWt1enRsZTRnTVkKLS0tIHR4RG1Mb0dPb3Jzblgydk9UUTRu
            WUdxOUp0aGJkeHNNUlF4ZjJRVEpOSlkKB4MdWU93tR3nIxfx7nSj1kPfrpKjCeGx
            inq/xYxdvvkVv0qOPtgU+Tq7ahF+SScEwvShuOg3vnXm/Ivs/0vJ+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T19:25:29Z"
    mac: ENC[AES256_GCM,data:4Cb350apweyEFPkVtxKlfdTliSCDbXLJ6V1fAVKKIh1WroyV5WCc2XJSjcsCl7rGm/l9Nop4HPqVyvQI9HUQK4JAZQ41NMWrUcawVF9UNxlCVjJIBHPyy4c6O1gYjKDoSCB+ps3axDpK4GTfQ41zxdGl54RZclq6Ahtl+KjIvlc=,iv:BkwSYBsfdt9yIuVBEj65rzWCZkSToryeSycpr3WsWDM=,tag:AqBOEK52Z4nY1GmZEmxcOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
