---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-config-v1
  namespace: mail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: ceph-block
