apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn-gateway
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:nlRtHjRwAg==,iv:kx71UhKINQ54rcal3BXwJDBUTJAfOkfABCmbuvL4sYc=,tag:edLCQR0HYD7RKBYzkjex5g==,type:str]
    VPN_SERVER_COUNTRIES: ENC[AES256_GCM,data:BWXO,iv:kfnkBc2z7QrA4FV491mUCsGi4fdEuupMsLIuza9c+MY=,tag:h6RjeWhMXpPbkfLxpdYYMQ==,type:str]
    VPN_SERVER_HOSTNAMES: ENC[AES256_GCM,data:nvWqV6NEQB7M0tddew==,iv:ZSer3BK6s7VaRj/0306ngt/DKjp5K6GKct62/kpTK6g=,tag:qKqimhVRtq+HFFOBcSZeLQ==,type:str]
    VPN_SERVER_CITIES: ENC[AES256_GCM,data:oxH+POxFW7fj,iv:FgfelZ66RcdZ8zxXJey95A1cfPETicW/oZZhqqd7yx0=,tag:Fk+TcxTRo5du/81dJLTS3g==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:hVM/eD0=,iv:ZNrjqLRiBnKzPjeqD1d0tZ/5B2/WCRHeAVvwEG4ZfXk=,tag:iUyjBkpl1BxouqumYp/E+A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZA6EC7ZVwjYBUzcPWHDLOcot/TzRxxjc0aKLJjoWSCch/ttmLYhnUfBLHng=,iv:kfAx2+X8xjNkux286S288QBvQxs2ZbQ8IznZcKGwWE0=,tag:C+PUXvmfKXdV6wQxUNClrA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:VyQEu+XEbXPBTeL8NT/nCQ==,iv:9zdvhc6mUMfVRHj7knv4P9HEwwSTo0iaNmUsjnGKG6M=,tag:CRxzQ7kGS1KVUOXAB0qSew==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:SpRtJAJut3QQRXDhpQ==,iv:IAT8LNWdoqthZ7TrKRBwbh0laKxN/+WsknjiMogEMEc=,tag:V6uc+eQe4RHoBi0gfWyN8Q==,type:str]
    SECRET_VPN_BT_FORWARD_PORT_1: ENC[AES256_GCM,data:dYrpKKQ=,iv:KBAhNAud84NJcmiBN1nqVcsXICveZ/sS1Id4k7DWphY=,tag:29VGhm0JoooN/iIli3JilA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcS9KNVU2YzNIWmJML1oy
            RjRkUHhrL1F3M3R3MXJodHVZUmdhazFWU0NVCmRkVmh2UGpLdG1sbUVza0JrR3Y1
            QXlaOGJjVDhNMlA4MXZRTm1BRm5TcDQKLS0tIGZ5dTR3bWtuNVJidndFdjJBT3Bm
            b1Y5T2NVaXZrN2lZRGw2dkxmUmlDQzAKYaoyKM2mm/qQeqnVlykDWYwAIU1zvDFt
            WduJzwGuzO+GEpQcSqo91JI4KwGNWPICGHQu7HTunqB4eLlsB4g95g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T20:46:12Z"
    mac: ENC[AES256_GCM,data:yubDTM8Gv9SKopVjrO6CF2yhGvEpmTfgoiWZKKYH/veibn//QL4sXT7ptw2qCiw4/inf6PgTCKqix5CgfrnSi/IBcDb9IdmEm36jw1OHG4pJeBX1rfSed1UR9fHJbwUCi8eBMzBA9qn0wIfX4JlFQ5HY50SnEjQunMcX3DOO+iI=,iv:3u1jhSwLDDWQCSyrPqGIf5wu9K03gyjYnoN2HP+/7dg=,tag:nvzv2u57E2VgifWFah1qKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
