apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn-gateway
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:nlRtHjRwAg==,iv:kx71UhKINQ54rcal3BXwJDBUTJAfOkfABCmbuvL4sYc=,tag:edLCQR0HYD7RKBYzkjex5g==,type:str]
    VPN_SERVER_COUNTRIES: ENC[AES256_GCM,data:BWXO,iv:kfnkBc2z7QrA4FV491mUCsGi4fdEuupMsLIuza9c+MY=,tag:h6RjeWhMXpPbkfLxpdYYMQ==,type:str]
    VPN_SERVER_HOSTNAMES: ENC[AES256_GCM,data:nQ+vzVijJqKmT6i5hQ==,iv:PzWutcinT3FGGMzKBAa/LazlqlliiSGdaH3inpoa9U0=,tag:UBgFkAk7x2L+vHWv9E07HA==,type:str]
    VPN_SERVER_CITIES: ENC[AES256_GCM,data:oxH+POxFW7fj,iv:FgfelZ66RcdZ8zxXJey95A1cfPETicW/oZZhqqd7yx0=,tag:Fk+TcxTRo5du/81dJLTS3g==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:hVM/eD0=,iv:ZNrjqLRiBnKzPjeqD1d0tZ/5B2/WCRHeAVvwEG4ZfXk=,tag:iUyjBkpl1BxouqumYp/E+A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:+GmFrIr+O3U1lCLgeesWvs5M9z6JbHmpuPAwRoJ/neFJPuUh/CH6v5LAY9w=,iv:T5v9kXsRtHXkXJXpAg38KN5Fns82tKaXKPK9eHoRZ4E=,tag:TMExGlYyQK5GQl66oc4vHA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:JI+CxOH3OXsie/l4Zh3mAw==,iv:PrISNt0Q4xu6Kf78ZonEs+Bvo3g2uogzLUnadrigchE=,tag:H7Xos9HbWRVJqwkCH/37Kw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:TGpCUN0vh8OtWOQLbQ==,iv:lkvw7YoZWqqMnZhgXVwObLgeaGnggWz4XdcOtJx90B4=,tag:9UpBMFVHHLfTj+sP6HH6aA==,type:str]
    SECRET_VPN_BT_FORWARD_PORT_1: ENC[AES256_GCM,data:q9s4UfY=,iv:8TeRwODK8g2atU8kGnryFHwXkdx1LNJgABUhQeMpmIA=,tag:ICLp8toyk7yKSabfnqgeUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vuvrs7evuks8zjl949dl2mcn4elxz0578cs03tnc63lt5aej49xqv92j8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcS9KNVU2YzNIWmJML1oy
            RjRkUHhrL1F3M3R3MXJodHVZUmdhazFWU0NVCmRkVmh2UGpLdG1sbUVza0JrR3Y1
            QXlaOGJjVDhNMlA4MXZRTm1BRm5TcDQKLS0tIGZ5dTR3bWtuNVJidndFdjJBT3Bm
            b1Y5T2NVaXZrN2lZRGw2dkxmUmlDQzAKYaoyKM2mm/qQeqnVlykDWYwAIU1zvDFt
            WduJzwGuzO+GEpQcSqo91JI4KwGNWPICGHQu7HTunqB4eLlsB4g95g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T22:30:19Z"
    mac: ENC[AES256_GCM,data:22CbbVqrhPL4mXC1b+UMsvpb4tKy1ZIxdlrPAxalrMjiBA5xbmDLL/F2EZ14OOMy9dd6Hn1QQUr+0YCoWmuzOKzdmrfcpz6/MmivYDR5ml/nYSYL+m0v32RNmfkGIVxMfJTF5xCIMwbxfC1D7wqQe+zcJdAsSeCQu823BTe94B4=,iv:RmNkSLzd4tsMz90cojb80If33UteeWrtEuiekIovLMw=,tag:2O6HIWI3iRZ5MArIClhB1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
