---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.26.10.100"
  METALLB_LB_RANGE: "10.26.10.200-10.26.10.250"
  METALLB_K8S_GATEWAY_ADDR: "10.26.10.200"
  METALLB_INGRESS_ADDR: "10.26.10.201"
