---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
