---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      type: statefulSet
    image:
      repository: louislam/uptime-kuma
      tag: 1.19.0
    service:
      main:
        ports:
          http:
            port: 3031
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:alert-circle-check
        hosts:
          - host: &host "status.donohoo.io"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      volumeClaimTemplates:
        - name: config
          mountPath: /app/data
          accessMode: ReadWriteOnce
          size: 4Gi
          storageClass: nfs-fast
          labels:
            snapshot.home.arpa/enabled: "true"
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          memory: 150Mi
