---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: louislam/uptime-kuma
      tag: "latest"
    env:
      TZ: "America/Chicago"
      UPTIME_KUMA_PORT: 3001
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "robot-happy"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
      - name: config
        mountPath: /app/data
        accessMode: ReadWriteOnce
        size: 4Gi
        storageClass: nfs-fast
        retain: true
        labels:
          snapshot.home.arpa/enabled: "true"
